### PR TITLE
simplify coffee compilation

### PR DESCRIPTION
**Pull request by notslang**
Hey! Over at Carrot Creative we're building a tool called [ship](https://github.com/carrot/ship) for deploying static sites (mostly). So I'm thinking about using nsync for a lot of the file moving & I'm willing to help to make it stable.

Anyway, this PR makes it a bit easier to build the coffeescript (and a couple other changes). Tell me what you think! :smile:

### CODE REVIEW

**Comment by notslang** [comment]
PS: Next I'm getting rid of most of that argument parsing logic and replacing it with [argparse](https://github.com/nodeca/argparse). Which will deal with validation, the `--version` thing, and help text (auto-generated)
image

**Comment by notslang** [comment]
ok, I haven't heard back from you for 6 days, so imma close this PR, otherwise it's going to get polluted with all the commits that I'm making on my fork. Feel free to comment & I'll reopen

**Comment by jnordberg** [comment]
Hey, sorry i've been busy. I'll get back to you on this when i get some spare time. My first impressions is that we have different ideas of how nsync should work :)

**Comment by notslang** [comment]
no prob & I'm sure we do : )

**Pull request closed without merging**
